name: Translation Tuesday

on:
  schedule:
    - cron:  '0 0 * * TUE'
  workflow_dispatch:

jobs:
  translation:
    name: translation_tuesday
    if: ${{ github.repository_owner == 'withastro' && github.event.commits[0].message != '[ci] format' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - id: message
        name: Format Discord message
        env:
          COMMIT_AUTHOR: ${{ github.event.commits[0].author.name }}
          COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
          COMMIT_ID: ${{ github.event.commits[0].id }}
        run: pnpm tsm --require=./scripts/lib/filter-warnings.cjs ./scripts/tuesday-bot.ts
      
      - name: Send a Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "${{ steps.message.outputs.DISCORD_MESSAGE }}"
